### POST request to create patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
    "name": "Tyler Durden",
    "email": "tylerapi@gmail.com",
    "address": "123 street fight club",
    "dateOfBirth": "1985-04-25",
    "registeredDate": "2025-04-23"
}

###